class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '映像関連' },
    { id: 3, name: 'オーディオ関連' },
    { id: 4, name: '情報家電' },
    { id: 5, name: 'キッチン家電' },
    { id: 6, name: '生活家電' },
    { id: 7, name: '健康・美容家電' },
    { id: 8, name: '季節家電' },
    { id: 9, name: 'ソファ' },
    { id: 10, name: 'チェア・椅子' },
    { id: 11, name: 'テーブル' },
    { id: 12, name: 'デスク・机' },
    { id: 13, name: '収納家具' },
    { id: 14, name: 'キッチン収納・食器棚' },
    { id: 15, name: 'テレビボード・テレビ台' },
    { id: 16, name: 'ハンガーラック・コートハンガー' },
    { id: 17, name: '玄関収納・小物' },
    { id: 18, name: 'ライト証明' },
    { id: 19, name: 'ベッド' },
    { id: 20, name: '寝具・タオル' },
    { id: 21, name: 'ミラー・ドレッサー' },
    { id: 22, name: 'ラグ・カーペット' },
    { id: 23, name: 'クッション' },
    { id: 24, name: 'ガーデンファニチャー・屋外家具' },
    { id: 25, name: 'キッズ家具・ベビー用品' },
    { id: 26, name: '時計' },
    { id: 27, name: '花器・プランター' },
    { id: 28, name: 'オブジェ・アート' },
    { id: 29, name: '食器・テーブルウェア' },
    { id: 30, name: 'キッチン用品' },
    { id: 31, name: '雑貨・その他インテリア家具' },
    { id: 32, name: '洋服' },
    { id: 33, name: 'ゲーム・おもちゃ' },
    { id: 34, name: 'ホビー・楽器' },
    { id: 35, name: 'PC周辺機器' },
    { id: 36, name: 'アウトドア' },
    { id: 37, name: 'DIY・工具' },
    { id: 38, name: 'ハンドメイド・手芸' },
    { id: 39, name: '車・バイク・自転車' },
  ]

  include ActiveHash::Associations
  has_many :items
end